name=MCP2515
version=2.0.1
author=MH-Tobi
maintainer=MH-Tobi
sentence=Library for the MCP2515-CAN-Controller.
paragraph=Library for controlling the MCP2515-CAN-Controller.
category=Communication
architectures=*
url=https://github.com/MH-Tobi/MCP2515
includes=MCP2515.h
