; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_deps = throwtheswitch/Unity@^2.6.0
check_tool = cppcheck, clangtidy ;pvs-studio
test_framework = unity
test_build_src = yes
;test_filter =
    ;api/test_changeBaudRate
    ;api/test_changeInterruptSetting
    ;api/test_check4FreeTransmitBuffer
    ;api/test_check4InterruptFlags
    ;api/test_check4Receive
    ;api/test_check4Rtr
    ;api/test_disableFilterMask
    ;api/test_enableFilterMask
    ;api/test_fillTransmitBuffer
    ;api/test_getAllFromReceiveBuffer
    ;api/test_getDataFromReceiveBuffer
    ;api/test_getDlcFromReceiveBuffer
    ;api/test_getFrameFromReceiveBuffer
    ;api/test_getIdFromReceiveBuffer
    ;api/test_getRtrFromReceiveBuffer
    ;api/test_init
    ;api/test_releaseReceiveBuffer
    ;api/test_resetInterruptFlag
    ;api/test_setClockFrequency
    ;api/test_setConfigurationMode
    ;api/test_setDataOrder
    ;api/test_setFilter
    ;api/test_setInterruptFlag
    ;api/test_setListenOnlyMode
    ;api/test_setLoopbackMode
    ;api/test_setMask
    ;api/test_setNormalMode
    ;api/test_setReCheckEnabler
    ;api/test_setSleepMode          ; always with an error
    ;api/test_setSpiFrequency
    ;api/test_setSpiMode
    ;api/test_setSpiPins
    ;functional/test_Filter_and_Mask_Feature
    ;functional/test_Interrupt_Feature
    ;functional/test_ReCheck_Feature
